# Generated by Django 6.0.7 on 2026-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('logo', models.URLField(blank=True, max_length=500, verbose_name='URL du Logo')),
                ('specialization', models.CharField(max_length=255, verbose_name="Spécialisation / Domaine d'activité")),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='Site Web officiel')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, verbose_name='Page LinkedIn')),
                ('description', models.TextField(verbose_name='Description & Services')),
                ('region', models.CharField(default='Dakar', max_length=100, verbose_name='Région / Ville (Sénégal)')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse physique')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Leader du secteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise biomédicale',
                'verbose_name_plural': 'Entreprises biomédicales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'appareil")),
                ('category', models.CharField(choices=[('Laboratoire', 'Laboratoire'), ('Imagerie', 'Imagerie médicale'), ('Bloc opératoire', 'Bloc opératoire'), ('Cardiologie', 'Cardiologie'), ('Réanimation', 'Réanimation & Urgences')], default='Laboratoire', max_length=100, verbose_name='Spécialité / Catégorie')),
                ('image', models.URLField(blank=True, max_length=500, verbose_name="URL de l'image")),
                ('description', models.TextField(verbose_name='Description clinique & aperçu')),
                ('working_principle', models.TextField(verbose_name='Principe de fonctionnement')),
                ('maintenance_protocol', models.TextField(verbose_name='Protocole de maintenance préventive')),
                ('source_url', models.URLField(max_length=500, verbose_name='Lien de la source obligatoire')),
                ('verified_by', models.CharField(default="Comité d'Expertise Biomédicale du Sénégal (AETQBM)", max_length=255, verbose_name='Vérifié par')),
                ('views_count', models.PositiveIntegerField(default=1200, verbose_name='Nombre de vues')),
                ('badge_label', models.CharField(default='New Tech', max_length=50, verbose_name='Badge / Étiquette')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Appareil en vedette / Appareil du jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appareil biomédical',
                'verbose_name_plural': 'Appareils biomédicaux',
                'ordering': ['-created_at'],
            },
        ),
    ]
